### ISSUE TITLE
UserStory1-Add List of stories

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#1]
## Value proposition

As a user
I want to see a list of my saved stories 
in order to easily access and manage my stories

## Description

![userstory1wireframe](https://user-images.githubusercontent.com/127031083/236158370-cf8f248a-71f9-4017-91f7-bb4fbdcabf3c.png)

## Acceptance criteria

- [ ] The app has a page that displays a list of all saved stories
- [ ] Each story in the list displays its title, cover image, and creation date.
- [ ] you can scroll if necessary

## Tasks

- [ ] create a branch
- [ ] create data in db.js
- [ ] create StoryList component
- [ ] render the list of saved stories
- [ ] Add cover images and creation date to each story component 
- [ ] Style the list of saved stories

Size: Medium

**Comment by mbosselmann** [comment]
Hi Darko,
I like your first user story! 👍 But I have some remarks for you to consider before moving further:

## Description
- "[image of wireframe]" this can be removed. It is just a placeholder. :)

## Acceptance Criteria
- your acceptance criteria are more the tasks of a developer than what the user will see
- the criterion "you can scroll if necessary" is ok though
- check the example of your fellow students and the examples of our agile workflow and user stories session to get a better understanding of what the acceptance criteria for this user story should be

## Tasks
- I think you do not need to create a new page as you only need one page that is already part of your capstone project or? 🤔 
- I think the refactoring task is not necessary for your first user story, but really good that you thought about this 👍 
- Usually we recommend to not start with implementing the backend as it is easier to start with a db.js with your example data. This would be easier and you can think about creating a database connection later during your capstone project when it might be useful to have access to a the stored data via multiple devices
- this would also reduce the complexity of your user story 🤔

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by DarkoKrezic** [comment]
Hi  Mareike,
thank you for your tips!
I did some changes to it. I'd be happy if you take a look.

**Comment by mbosselmann** [comment]
Hi Darko,
you rock! 🪨 I have two remarks for your **tasks:**

- "fetch the list of saved stories" you do not need to fetch the list you can import the data and work with it directly
- "Add a click event to each story component" the click event is of no use for now or? 🤔 If this is to get later to the details page of each story, then for now it is not necessary to implement a click event. Therefore, I would remove this task.

A nice to have would be to have some example names of your stories instead of story name for a more realistic wireframe. And it is typical to display an image like this:

![Untitled-2023-05-02-1722(2)](https://user-images.githubusercontent.com/77329824/236152879-35866ed1-3395-444b-8ba9-ca323cdc3adb.png)

Feel free to ask me if you have questions. :)

**Comment by DarkoKrezic** [comment]
Hi Mareike, 
thx again, that helps a lot. I did the suggested changes, please check it out!

**Comment by mbosselmann** [comment]
Hi Darko,
you rock! 🪨 
I approve your first user story. 🥳
