### ISSUE TITLE
userstory6

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#12]
## Value proposition

As a user, I want to be able to access a "Use Storyteller" button on the Create New Story page. When I click on the button, I want to be taken to a new page with an input form where I can provide some information about what I would like to have in my story.
In order tobe able to easily generate new stories based on my input

## Description

![userstory6](https://github.com/DarkoKrezic/capstone-projekt/assets/127031083/d896ba02-6a03-4eae-b5cc-7cf19ee1d76e)

## Acceptance criteria

- [ ] There should be a "Use Storyteller" button on the Create New Story page.
- [ ] there should be short description for the user on how to make the prompt
- [ ] Clicking on the "Use Storyteller" button should take the user to a new page with an input form
- [ ] The input form should include a textarea where the user can enter a brief description of what they want the story to be about
- [ ] there should be a button to submit the prompt

## Tasks

- [ ] Add a "Use Storyteller" button to the Create New Story page.
- [ ] create an element with the description text
- [ ] Implement a mechanism for redirecting the user to a new page when the button is clicked.
- [ ] Create an input form with a textarea for the user to enter a brief description of the story they want to create.
- [ ] create a button to submit the entry
- [ ] some styling
Size:s

**Comment by HenrikeStahlhut** [comment]
> In order tobe able to easily generate new stories based on my input

Will you use AI to generate the stories in future US? If yes, maybe you could add that for a better understanding. But thats's just a suggestion, otherwise the US looks good 😁
