### ISSUE TITLE
userstory7 -fetchnewstory

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#13]
## Value proposition

As a user
I want to be able to submit my input form and receive a generated story from the ChatGPT API. If the generated story isn't exactly what I want, I want to be able to edit the story and save it
in order to easily create unique and personalized stories for my StoryList using Chat GPT API

## Description

![userstory7](https://github.com/DarkoKrezic/capstone-projekt/assets/127031083/83ed81b3-3f55-40f5-8fa1-943e6b0377a6)

## Acceptance criteria

- [ ] The input form should include fields for the user to enter the prompt for their story.
- [ ] When the user submits the input form, users prompt is used to generate our "StoryObject prompt" , which  then should be sent to the ChatGPT API and a generated story object should be returned.
- [ ] Generated story object response should contain a generated Title of the story , generated story Text and a prompt for the generation of a image using openAI Image creator. 
- [ ] this prompt is then used to generate the coverImage for the story , which is now along side our Title and Story text being used to create  newGeneratedStory
- [ ] The user should be redirected to the Edit Story page, which should be pre-populated with the newGeneratedStory data.

## Tasks

- [ ] Update the "UseStorytellerForm.js" component to include fields for the user to enter the prompt for their story.
- [ ] Modify the form submission process to use the user's prompt to generate a "StoryObject prompt".
- [ ] Send the "StoryObject prompt" to the ChatGPT API and receive a generated story object response.
- [ ] Extract the generated title, story text, and prompt for image generation from the API response.
- [ ] Use the extracted prompt for image generation to create a request to the OpenAI Image Creator API.
- [ ] Send the image generation request to the OpenAI Image Creator API and receive the generated cover image in the response.
- [ ] Combine the generated title, story text, and cover image to create a new generated story object.
- [ ] Redirect the user to the Edit Story page, pre-populated with the data of the new generated story.

Size:mid

**Comment by MerleMak** [comment]
Hi Darko! Cool App :)
Make sure to keep the quite strict structure of the Value Proposition (also including the format) like so:

As a user,
I want to be able to submit my input form and receive a generated story from the ChatGPT API,
in order to [ insert REASON why the User will want a feature like this ]

The rest of you Value proposition ("If the generated story isn't exactly what I want, I want to be able to edit the story and save it") Should be either another Userstory OR part of the Acceptance Criteria :)

Also, try to be a bit more specific in the Tasks. Instead of saying "Implement a mechanism  for..." maybe its better to specify which exact mechanism you are thinking about :)

I am excited to see the feature! Nice work :)

**Comment by DarkoKrezic** [comment]
Hey Merle, thanks for overlooking! 🙏  I made some changes based on your suggestions. Please take look, if u have time for it. Thx!

**Comment by MerleMak** [comment]
Very nice work!!
