### ISSUE TITLE
User Story2- Show Story details 

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#2]
## Value proposition

As a user 
I want to be able to view the details of a story and easily navigate back to the list of saved stories
in order to be able to browse and select other stories

## Description

![userstory2 darkocap](https://user-images.githubusercontent.com/127031083/236169366-df5134df-7e32-4dee-8b3d-e0bff101a9ac.png)

## Acceptance criteria

- [ ] The app has a story detail page that displays the full details of a selected story
- [ ] The story detail page includes the story title, cover image, creation date, the full text of the story, and a "back to list" button
- [ ] Clicking the "back to My Stories" button returns the user to the list of saved stories

## Tasks

- [ ] Create a new component for the story detail page
- [ ] Pass the selected story data to the story detail page component and render the story details on the story detail page
- [ ] Link the story detail page to the list of saved stories, so that the user can access it by clicking on a story in the list
- [ ] Create a new component for the "back to list" button
- [ ] Add the "back to My Stories" button component to the story detail page
- [ ] Implement the functionality to return to the list of saved stories when the button is clicked

Size:
