### ISSUE TITLE
User story3- create a new story

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#3]
## Value proposition

As a user
I want to be able to add new stories
in order to create stories and save them

## Description

![userstory3 darkocap](https://user-images.githubusercontent.com/127031083/236191514-1e1a3f6e-aa0f-4d08-b670-84de31241165.png)

## Acceptance criteria

- [ ] The "My Stories" page includes an "Add new story" button that navigates to the "New Story" page when clicked
- [ ] The "New Story" page includes a form with fields for the story title, cover image, and full text, as well as a "Save" button to add the new story to the list of saved stories

## Tasks

- [ ] Create a new component for the "Add New Story" form
- [ ] Implement a form with fields for title, author, image upload, and story text
- [ ] Implement an image preview feature so the user can see the image they uploaded before submitting the form
- [ ] Implement a "Save" button that adds the new story to the user's collection
- [ ] Implement navigation to the "My Stories" page after submitting the form
- [ ] Update the "My Stories" page to dynamically display the new story that was added

Size: mid

**Comment by HenrikeStahlhut** [comment]
LGTM 🔥
