### ISSUE TITLE
User story4-edit story

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#6]
## Value proposition

As a user
I want to be able edit a story from my list
in order to update content as needed

## Description

![user story4 darko cap ](https://user-images.githubusercontent.com/127031083/236759667-c5304ee9-6beb-4f5f-b7c2-9503aeb1f523.png)

## Acceptance criteria

- [ ] The story detail page includes buttons for editing the story
- [ ] Clicking the edit button takes the user to a new page with a form pre-populated with the existing story information 
- [ ] The user can submit the form to update the story
- [ ] The story is updated in the database as appropriate.
- [ ] The user is redirected back to the "My Stories" page after editing a story

## Tasks

- [ ] Add edit button to the story detail page
- [ ] Create a new page for editing a story with a form pre-populated with the existing story information
- [ ] Add a handler function for submitting the edit form
- [ ] Redirect the user back to the "My Stories" page after editing or deleting a story

Size: mid

**Comment by mbosselmann** [comment]
Hi Darko,
these are two user stories. The edit functionality is one user story and the delete functionality is another user story as these are self-contained features. :) 
Please split this user story in two and post them again in our channel. 👀

**Comment by DarkoKrezic** [comment]
Hi Mareike,
thx for your tips, i split the story into 2. please check out the new user story4 first.thx

**Comment by BenRodProd** [comment]
Lgtm
