### ISSUE TITLE
User Story 5- Delete Story

### ISSUE THREAD

**Issue by DarkoKrezic** [DarkoKrezic/capstone-projekt#7]
## Value proposition

As a user
I want to be able to delete a story from my list 
in order to menage my content by removing unwanted content

## Description

![user story 5 darkocap](https://user-images.githubusercontent.com/127031083/236770010-7b54ecf9-2608-4ee9-af07-b38a69655a5a.png)

## Acceptance criteria

- [ ] The story detail page includes a delete button
- [ ] Clicking the button removes the story from user's list

## Tasks

- [ ] Add a delete button to the story detail page
- [ ] Remove the story from the database upon delete button click
- [ ] Redirect the user back to the "My Stories" page after deleting the story

Size: mid
